
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public final class UpdateProductDetails extends javax.swing.JFrame {
    String Productid="";
    /**
     * Creates new form viewProductDetails
     * @param selectedProduct
     */
    public UpdateProductDetails(String selectedProduct) {
        Productid=selectedProduct;
        
        initComponents();
        test.setText(Productid);
        loadTblData();
    }

    private UpdateProductDetails() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    void loadTblData(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st=con.createStatement();
            
            PreparedStatement ps=con.prepareStatement("select * from product where product_id=?");
            ps.setString(1, Productid);
        
        
            ResultSet rs=ps.executeQuery();
            
            
            
            //String sql="select * from product where product_id=?";
            
            
            //ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                
                String product_id=rs.getString("product_id");
                String product_name=rs.getString("product_name");
                String category=rs.getString("category");  
                String manufacturer=rs.getString("manufacturer");
                String description=rs.getString("description");
                String cost_price=rs.getString("cost_price");
                String location_code=rs.getString("location_code");  
                String stock_code=rs.getString("stock_code"); 
                String quantity=rs.getString("quantity");
                String supplier_id=rs.getString("supplier_id");
                String supplier_name=rs.getString("supplier_name");  
                String supplier_address=rs.getString("supplier_address");
                String supplier_contact=rs.getString("supplier_contact"); 
                String contact_email=rs.getString("contact_email");         
                
                productId.setText(product_id);
                productName.setText(product_name);
                //productId.setText(category);
                productManufacturer.setText(manufacturer);
                productDescription.setText(description);
                productCostPrice.setText(cost_price);
                productLocationCode.setText(location_code);
                productStockCode.setText(stock_code);
                productQuantity.setText(quantity);
                supplierId.setText(supplier_id);
                supplierName.setText(supplier_name);
                supplierAddress.setText(supplier_address);
                supplierContact.setText(supplier_contact);
                supplierEmail.setText(contact_email);
   
            }
                
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(main_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        productId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        productManufacturer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productCostPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        productLocationCode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        productStockCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        productQuantity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        productDescription = new javax.swing.JTextField();
        productCategory = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        supplierId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        supplierName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        supplierAddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        supplierContact = new javax.swing.JTextField();
        supplierEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Product Information");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Product ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Category");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 220, 40));

        productName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 220, 40));

        productManufacturer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productManufacturer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 220, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Manufacturer");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 220, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cost Price");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 40));

        productCostPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productCostPrice.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productCostPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Location Code");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 220, 40));

        productLocationCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productLocationCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productLocationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 220, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Stock Code");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 220, 40));

        productStockCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productStockCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productStockCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 220, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 220, 40));

        productQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productQuantity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 220, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Description");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 40));

        productDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productDescription.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(productDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 980, 40));

        productCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrical Supplies", "Plumbing Supplies", "Building Materials", "Tools and Equipment", "Safety Equipment", "Fasteners and Hardware", "Paints and Coatings", "Flooring and Tiles", "HVAC (Heating, Ventilation, and Air Conditioning)", "Lighting Fixtures", "Roofing and Siding Materials", "Windows and Doors", "Concrete and Masonry Supplies", "Landscaping and Outdoor Equipment", "Kitchen and Bathroom Fixtures", "Insulation and Weatherproofing", "Lumber and Timber Products", "Metal and Steel Products", "Fencing and Gates", "Adhesives and Sealants" }));
        productCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(productCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 220, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Product Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 220, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1000, 310));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Supplier Information");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Supplier ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 40));

        supplierId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplierId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(supplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Supplier Name");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 220, 40));

        supplierName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplierName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(supplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 220, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Supplier Address");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 220, 40));

        supplierAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplierAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(supplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 220, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Contact No.");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 220, 40));

        supplierContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplierContact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(supplierContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 220, 40));

        supplierEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplierEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(supplierEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Email");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1000, 230));

        test.setText("jLabel17");
        getContentPane().add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 180, 30));

        jButton1.setText("Delete Product");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 140, 40));

        jButton2.setText("Close");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 140, 40));

        jButton3.setText("Update");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 140, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String productid=productId.getText();
        String productname=productName.getText();
        String productcategory=productCategory.getSelectedItem().toString();
        String productmanufacturer=productManufacturer.getText();
        String productdescription=productDescription.getText();
        String productcostPrice=productCostPrice.getText();
        String productlocationCode=productLocationCode.getText();
        String productstockCode=productStockCode.getText();
        String productquantity=productQuantity.getText();
        String supplierid=supplierId.getText();
        String suppliername=supplierName.getText();
        String supplieraddress=supplierAddress.getText();
        String suppliercontact=supplierContact.getText();
        String supplieremail=supplierEmail.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            String sql = "update product set product_id=?, product_name=?, category=?, manufacturer=?, description=?, cost_price=?, location_code=?, stock_code=?, quantity=?, supplier_id=?, supplier_name=?, supplier_address=?, supplier_contact=?, contact_email=? where product_id=?";
            PreparedStatement ptsmt = con.prepareStatement(sql);
            
            ptsmt.setString(1,productid);
            ptsmt.setString(2,productname);
            ptsmt.setString(3,productcategory);
            ptsmt.setString(4,productmanufacturer);
            ptsmt.setString(5,productdescription);
            ptsmt.setString(6,productcostPrice);
            ptsmt.setString(7,productlocationCode);
            ptsmt.setString(8,productstockCode);
            ptsmt.setString(9,productquantity);
            ptsmt.setString(10,supplierid);
            ptsmt.setString(11,suppliername);
            ptsmt.setString(12,supplieraddress);
            ptsmt.setString(13,suppliercontact);
            ptsmt.setString(14,supplieremail);
            ptsmt.setString(15,Productid);
            
            ptsmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            
            

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(main_interface.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Update Failed");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure want to delete", "Delete", dialogButton);
        
        if(dialogResult == 0) {
            System.out.println("Yes option");

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            String sql = "delete from product where product_id=?";
            PreparedStatement ptsmt = con.prepareStatement(sql);
            
            ptsmt.setString(1,Productid);
            
            ptsmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted Successfully");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(main_interface.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Delete Failed");
        }
        dispose();
    }
        else {
            System.out.println("No Option");
        } 
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProductDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> productCategory;
    private javax.swing.JTextField productCostPrice;
    private javax.swing.JTextField productDescription;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField productLocationCode;
    private javax.swing.JTextField productManufacturer;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productQuantity;
    private javax.swing.JTextField productStockCode;
    private javax.swing.JTextField supplierAddress;
    private javax.swing.JTextField supplierContact;
    private javax.swing.JTextField supplierEmail;
    private javax.swing.JTextField supplierId;
    private javax.swing.JTextField supplierName;
    private javax.swing.JLabel test;
    // End of variables declaration//GEN-END:variables
}
